Site: "SITE_NAME"
varnish_mem: "24G"
varnish_transient_mem: "1G"

monitoring:
  es: true
  snmp: true

ports:
  varnish_container_port: 80
  varnish_port: 6081
  snmp_container_port: 3401
  snmp_port: 3401

nodeSelector:
  varnish: cvmfs-slate

acl: |-
  "localhost";
  "72.36.96.0"/24; 
  "149.165.224.0"/23; 
  "192.170.240.0"/23;

backends:
  - name: fermilab_2
    host: 2620:6a:0:8421::244
    port: 8000
  - name: bnl_1
    host: 192.12.15.180
    port: 8000
  - name: cern_2
    host: 2001:1458:301:cd::100:41d
    port: 80
  - name: fermilab_1
    host: 131.225.189.138
    port: 8000
  - name: bnl_2
    host: 192.12.15.179
    port: 8000
  - name: cern_1
    host: 128.142.194.109
    port: 80

resources:
  requests:
    cpu: "4"
    memory: "33Gi"
  limits:
    cpu: "48"
    memory: "48Gi"

### SLATE-START ###
Instance: slate01
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
