apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: {{ template "nginx.name" . }}
    instance: {{ .Values.Instance | quote }}
---
{{ if .Values.Ingress.Enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.Class }}
    cert-manager.io/cluster-issuer: {{ .Values.Ingress.Issuer }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.Ingress.Issuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
{{- if .Values.Ingress.TlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.Ingress.Subdomain }}.{{ .Values.SLATE.Cluster.DNSName }}
    secretName: nginx-{{ .Values.Instance}}-tls
{{- end }}
  rules:
  - host: {{ .Values.Ingress.Subdomain }}.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ template "nginx.fullname" . }}
            port:
              number: 80
        pathType: ImplementationSpecific
{{ end }}
