apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "perfsonar-testpoint.fullname" . }}
  labels:
    app: {{ template "perfsonar-testpoint.name" . }}
    chart: {{ template "perfsonar-testpoint.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
    instanceID: {{ .Values.SLATE.Instance.ID | quote  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "perfsonar-testpoint.name" . }}
      chart: {{ template "perfsonar-testpoint.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "perfsonar-testpoint.name" . }}
        chart: {{ template "perfsonar-testpoint.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      hostNetwork: true
      {{ if .Values.CustomSupervisordConfig.Enabled  }}
      volumes:
      - name: supervisord-configuration
        configMap:
          name: perfsonar-testpoint-{{ .Values.Instance }}-supervisord-configuration
          items:
          - key: supervisord.conf
            path: supervisord.conf
            mode: 292
      {{ end }}
      containers:
      - name: perfsonar-testpoint
        image: perfsonar/testpoint:v5.0.2
        imagePullPolicy: Always
        securityContext: 
          privileged: true
        {{ if .Values.CustomSupervisordConfig.Enabled  }}
        volumeMounts:
        - name: supervisord-configuration
          mountPath: /etc/supervisord.conf
          subPath: supervisord.conf
        {{ end }}
      restartPolicy: Always
      {{ if .Values.nodeSelection }}
      nodeSelector:
        perfsonar: enabled
      {{ end }}
