{{ if .Values.HTTPLogger.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "condor-worker.fullname" . }}
  labels:
    app: {{ template "condor-worker.name" . }}
    chart: {{ template "condor-worker.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: logs
    protocol: TCP
    name: logs
  selector:
    app: {{ template "condor-worker.name" . }}
    instance: {{ .Values.Instance | quote }}
{{ end }}
