kind: Service
apiVersion: v1
metadata:
  name: {{ template "stashcache.fullname" . }}-xroot
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  selector:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  ports:
    - protocol: TCP
      name: xrootd
      port: 1094
      targetPort: 1094
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "stashcache.fullname" . }}-http
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  selector:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
