name: Notify API Server

on:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed
    branches:
      - gh-pages

jobs:
  notify:
    name: Notify
    uses: slateci/github-actions/.github/workflows/slate-updateapps.yml@v2
    secrets:
      slate_api_token: "${{ secrets.SLATE_API_TOKEN }}"
