# Resources:
# * https://github.com/marketplace/actions/helm-chart-releaser
# * https://github.com/helm/chart-releaser
# * https://blog.ediri.io/auto-docs-test-and-release-a-helm-chart-with-github-actions

name: Stable Release

on:
  push:
    branches:
      - master

env:
  HELM_VERSION: 3.8.1

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
